name: LLM
channels:
  - https://mirrors.ustc.edu.cn/anaconda/cloud/menpo/
  - https://mirrors.ustc.edu.cn/anaconda/cloud/bioconda/
  - https://mirrors.ustc.edu.cn/anaconda/cloud/msys2/
  - https://mirrors.ustc.edu.cn/anaconda/cloud/conda-forge/
  - https://mirrors.ustc.edu.cn/anaconda/pkgs/free/
  - https://mirrors.ustc.edu.cn/anaconda/pkgs/main/
  - https://mirrors.bfsu.edu.cn/anaconda/cloud/peterjc123/
  - https://mirrors.bfsu.edu.cn/anaconda/cloud/pytorch/
  - https://mirrors.bfsu.edu.cn/anaconda/cloud/menpo/
  - https://mirrors.bfsu.edu.cn/anaconda/cloud/bioconda/
  - https://mirrors.bfsu.edu.cn/anaconda/cloud/msys2/
  - https://mirrors.bfsu.edu.cn/anaconda/cloud/conda-forge/
  - https://mirrors.bfsu.edu.cn/anaconda/pkgs/main/
  - https://mirrors.bfsu.edu.cn/anaconda/pkgs/free/
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/pytorch/linux-64/
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/pytorch/
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main/
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free/
  - defaults
dependencies:
  - bzip2=1.0.8=he774522_0
  - ca-certificates=2023.05.30=haa95532_0
  - libffi=3.4.4=hd77b12b_0
  - openssl=3.0.10=h2bbff1b_0
  - pip=23.2.1=py310haa95532_0
  - python=3.10.12=he1021f5_0
  - setuptools=68.0.0=py310haa95532_0
  - sqlite=3.41.2=h2bbff1b_0
  - tk=8.6.12=h2bbff1b_0
  - tzdata=2023c=h04d1e81_0
  - vc=14.2=h21ff451_1
  - vs2015_runtime=14.27.29016=h5e58377_2
  - wheel=0.38.4=py310haa95532_0
  - xz=5.4.2=h8cc25b3_0
  - zlib=1.2.13=h8cc25b3_0
  - pip:
    - addict==2.4.0
    - aiohttp==3.8.5
    - aiosignal==1.3.1
    - aliyun-python-sdk-core==2.13.36
    - aliyun-python-sdk-kms==2.16.1
    - anyio==3.7.1
    - appdirs==1.4.4
    - apscheduler==3.10.1
    - asttokens==2.2.1
    - async-timeout==4.0.2
    - attrs==23.1.0
    - authlib==1.2.1
    - backcall==0.2.0
    - backoff==2.2.1
    - beautifulsoup4==4.12.2
    - bilibili-api-python==15.5.3
    - bleach==6.0.0
    - blis==0.7.10
    - bokeh==3.2.2
    - brotli==1.0.9
    - build==0.10.0
    - cachecontrol==0.12.14
    - cachetools==5.3.1
    - catalogue==2.0.9
    - certifi==2023.7.22
    - cffi==1.15.1
    - chardet==5.2.0
    - charset-normalizer==2.1.0
    - chispa==0.9.2
    - chroma-hnswlib==0.7.2
    - chromadb==0.4.5
    - cleo==2.0.1
    - click==8.1.6
    - colorama==0.4.6
    - coloredlogs==15.0.1
    - comm==0.1.4
    - confection==0.1.0
    - contourpy==1.1.0
    - cpm-kernels==1.0.11
    - crashtest==0.4.1
    - crcmod==1.7
    - cryptography==41.0.3
    - cycler==0.11.0
    - cymem==2.0.7
    - dataclasses-json==0.5.14
    - datasets==2.8.0
    - datetime==5.2
    - debugpy==1.6.7
    - decorator==5.1.1
    - dill==0.3.6
    - distlib==0.3.7
    - dnspython==2.4.1
    - docarray==0.37.0
    - docker-pycreds==0.4.0
    - dulwich==0.21.5
    - einops==0.6.1
    - elastic-transport==8.4.0
    - elasticsearch==8.9.0
    - exceptiongroup==1.1.2
    - executing==1.2.0
    - faiss-cpu==1.7.4
    - fastapi==0.99.1
    - fastjsonschema==2.18.0
    - filelock==3.12.2
    - filetype==1.2.0
    - flatbuffers==23.5.26
    - fonttools==4.42.0
    - frozenlist==1.4.0
    - fsspec==2023.6.0
    - gast==0.5.4
    - gitdb==4.0.10
    - gitpython==3.1.32
    - google-api-core==2.11.1
    - google-api-python-client==2.96.0
    - google-auth==2.22.0
    - google-auth-httplib2==0.1.0
    - google-auth-oauthlib==1.0.0
    - google-search-results==2.4.2
    - googleapis-common-protos==1.60.0
    - greenlet==2.0.2
    - grpcio==1.57.0
    - grpcio-status==1.57.0
    - grpcio-tools==1.56.2
    - h11==0.14.0
    - h2==4.1.0
    - hpack==4.0.0
    - html5lib==1.1
    - httpcore==0.17.3
    - httplib2==0.22.0
    - httptools==0.6.0
    - httpx==0.24.1
    - huggingface-hub==0.16.4
    - humanfriendly==10.0
    - hyperframe==6.0.1
    - icetk==0.0.4
    - idna==3.4
    - importlib-metadata==6.8.0
    - importlib-resources==6.0.1
    - installer==0.7.0
    - ipykernel==6.25.0
    - ipynb==0.5.1
    - ipython==8.14.0
    - ipywidgets==8.1.0
    - jaraco.classes==3.3.0
    - jaraco.context==4.3.0
    - jedi==0.19.0
    - jinja2==3.1.2
    - jmespath==0.10.0
    - joblib==1.3.1
    - jsonplus==0.8.0
    - jsonschema==4.19.0
    - jsonschema-specifications==2023.7.1
    - jupyter-bokeh==3.0.7
    - jupyter_client==8.3.0
    - jupyter_core==5.3.1
    - jupyterlab-widgets==3.0.8
    - keyring==23.13.1
    - kiwisolver==1.4.4
    - kor==0.13.0
    - langchain==0.0.262
    - langcodes==3.3.0
    - langsmith==0.0.18
    - lark==1.1.7
    - linkify-it-py==2.0.2
    - lockfile==0.12.2
    - loguru==0.7.0
    - lxml==4.9.3
    - manifest-ml==0.0.1
    - markdown==3.4.4
    - markdown-it-py==3.0.0
    - markupsafe==2.1.3
    - marshmallow==3.20.1
    - matplotlib==3.7.2
    - matplotlib-inline==0.1.6
    - mdit-py-plugins==0.4.0
    - mdurl==0.1.2
    - modelscope==1.4.3
    - monotonic==1.6
    - more-itertools==10.1.0
    - mpmath==1.3.0
    - msgpack==1.0.5
    - multidict==6.0.4
    - multiprocess==0.70.14
    - murmurhash==1.0.9
    - mutagen==1.46.0
    - mypy-extensions==1.0.0
    - nbformat==5.9.2
    - nest-asyncio==1.5.7
    - networkx==3.1
    - nltk==3.8.1
    - numexpr==2.8.4
    - numpy==1.23.5
    - oauthlib==3.2.2
    - onnxruntime==1.15.1
    - openai==0.27.8
    - openapi-schema-pydantic==1.2.4
    - orjson==3.9.4
    - oss2==2.18.1
    - overrides==7.4.0
    - packaging==23.1
    - pandas==1.5.3
    - panel==1.2.1
    - param==1.13.0
    - parso==0.8.3
    - pathtools==0.1.2
    - pathy==0.10.2
    - pexpect==4.8.0
    - pickleshare==0.7.5
    - pillow==10.0.0
    - pinecone-client==2.2.2
    - pinyin==0.4.0
    - pipe==2.0
    - pkginfo==1.9.6
    - platformdirs==3.10.0
    - plotly==5.16.0
    - poetry==1.5.1
    - poetry-core==1.6.1
    - poetry-plugin-export==1.4.0
    - posthog==3.0.1
    - preshed==3.0.8
    - prompt-toolkit==3.0.39
    - protobuf==4.23.4
    - psutil==5.9.5
    - ptyprocess==0.7.0
    - pulsar-client==3.2.0
    - pure-eval==0.2.2
    - py4j==0.10.9.7
    - pyarrow==12.0.1
    - pyasn1==0.5.0
    - pyasn1-modules==0.3.0
    - pycparser==2.21
    - pycryptodome==3.18.0
    - pycryptodomex==3.18.0
    - pydantic==1.10.12
    - pydub==0.25.1
    - pygments==2.15.1
    - pyparsing==3.0.9
    - pypdf==3.15.0
    - pypika==0.48.9
    - pypng==0.20220715.0
    - pyproject_hooks==1.0.0
    - pyreadline3==3.4.1
    - pyspark==3.4.1
    - pyspark-ai==0.1.15
    - python-dateutil==2.8.2
    - python-dotenv==1.0.0
    - python-magic==0.4.27
    - pytz==2023.3
    - pyviz-comms==2.3.2
    - pywin32==306
    - pywin32-ctypes==0.2.2
    - pyyaml==6.0.1
    - pyzmq==25.1.0
    - qdrant-client==0.11.10
    - qrcode==7.4.2
    - qrcode-terminal==0.8
    - rapidfuzz==2.15.1
    - redis==4.6.0
    - referencing==0.30.2
    - regex==2023.6.3
    - requests==2.31.0
    - requests-oauthlib==1.3.1
    - requests-toolbelt==1.0.0
    - responses==0.18.0
    - rich==13.5.2
    - rpds-py==0.9.2
    - rsa==4.9
    - safetensors==0.3.1
    - scikit-learn==1.3.0
    - scipy==1.11.1
    - sentencepiece==0.1.99
    - sentry-sdk==1.29.2
    - setproctitle==1.3.2
    - shellingham==1.5.0.post1
    - simplejson==3.19.1
    - six==1.16.0
    - smart-open==6.3.0
    - smmap==5.0.0
    - sniffio==1.3.0
    - sortedcontainers==2.4.0
    - soupsieve==2.4.1
    - spacy==3.6.0
    - spacy-legacy==3.0.12
    - spacy-loggers==1.0.4
    - sqlalchemy==1.4.49
    - sqlitedict==2.1.0
    - srsly==2.4.7
    - stack-data==0.6.2
    - starlette==0.27.0
    - sympy==1.12
    - tabulate==0.9.0
    - tenacity==8.2.2
    - thinc==8.1.10
    - threadpoolctl==3.2.0
    - tiktoken==0.4.0
    - tokenizers==0.13.3
    - tomli==2.0.1
    - tomlkit==0.12.1
    - torch==1.13.1
    - torchvision==0.15.2
    - tornado==6.3.2
    - tqdm==4.65.0
    - traitlets==5.9.0
    - transformers==4.26.1
    - trove-classifiers==2023.8.7
    - typer==0.9.0
    - types-requests==2.31.0.2
    - types-urllib3==1.26.25.14
    - typing-inspect==0.9.0
    - typing_extensions==4.7.1
    - tzlocal==5.0.1
    - uc-micro-py==1.0.2
    - unstructured==0.9.2
    - uritemplate==4.1.1
    - urllib3==1.26.16
    - uvicorn==0.23.2
    - validators==0.20.0
    - virtualenv==20.24.3
    - wandb==0.15.8
    - wandb-addons==0.1.0
    - wasabi==1.1.2
    - watchfiles==0.19.0
    - wcwidth==0.2.6
    - weaviate-client==3.22.1
    - webencodings==0.5.1
    - websockets==11.0.3
    - widgetsnbextension==4.0.8
    - wikipedia==1.4.0
    - win32-setctime==1.1.0
    - wolframalpha==5.0.0
    - xmltodict==0.13.0
    - xxhash==3.3.0
    - xyzservices==2023.7.0
    - yapf==0.40.1
    - yarl==1.9.2
    - yt-dlp==2023.7.6
    - zipp==3.16.2
    - zope.interface==6.0
prefix: D:\Anaconda3\envs\LLM

