wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.10.12
    cli_version: 0.15.8
    is_jupyter_run: true
    is_kaggle_kernel: false
    start_time: 1692069058.934279
    t:
      1:
      - 55
      - 86
      - 92
      - 95
      - 105
      2:
      - 1
      - 55
      - 86
      - 92
      - 95
      - 105
      3:
      - 23
      4: 3.10.12
      5: 0.15.8
      8:
      - 1
      - 3
      - 5
      9:
        2: langchain
    framework: torch
